### PR TITLE
Add parent project support

### PR DESCRIPTION
**Pull request by LucasVanHaaren**
Hi,

I have worked a bit to add parent project support like mentionned in https://github.com/takumakume/sbomreport-to-dependencytrack/issues/16. I successfully pushed some SBOMs with and without specified parent with a sbomreport generated by my local trivy-operator.
Seems to work well but I can't managed to pass the unit test `TestUpload_Run` (See the [stacktrace here](https://github.com/user-attachments/files/16246357/stacktrace_test.log)).

I also tried to use the provided sbomreport `testdata/v1alpha1.json` but I can't managed to push it to my dtrack instance with the following command : 

```bash
cat testdata/v1alpha1.json | sbomreport-to-dependencytrack --base-url "https://<REDACTED>" --api-key "<READACTED>" --project-name "some-test" --project-version "v1"
```

But I got the following 400 error : 

```
Error: {"status":400,"title":"The uploaded BOM is invalid","detail":"Schema validation failed","errors":["$.components[1].licenses[0].license: must be valid to one and only one schema, but 0 are valid","$.components[1].licenses[0].license: required property 'id' not found","$.components[1].licenses[0].license: required property 'name' not found","$.components[1].licenses[0]: must be valid to one and only one schema, but 2 are valid with indexes '0, 1'","$.components[2].licenses[0].license: must be valid to one and only one schema, but 0 are valid","$.components[2].licenses[0].license: required property 'id' not found","$.components[2].licenses[0].license: required property 'name' not found","$.components[2].licenses[0]: must be valid to one and only one schema, but 2 are valid with indexes '0, 1'","$.components[3].licenses[0].license: must be valid to one and only one schema, but 0 are valid","$.components[3].licenses[0].license: required property 'id' not found","$.components[3].licenses[0].license: required property 'name' not found","$.components[3].licenses[0]: must be valid to one and only one schema, but 2 are valid with indexes '0, 1'","$.components[4].licenses[0].license: must be valid to one and only one schema, but 0 are valid","$.components[4].licenses[0].license: required property 'id' not found","$.components[4].licenses[0].license: required property 'name' not found","$.components[4].licenses[0]: must be valid to one and only one schema, but 2 are valid with indexes '0, 1'","$.components[5].licenses[0].license: must be valid to one and only one schema, but 0 are valid","$.components[5].licenses[0].license: required property 'id' not found","$.components[5].licenses[0].license: required property 'name' not found","$.components[5].licenses[0]: must be valid to one and only one schema, but 2 are valid with indexes '0, 1'","$.components[6].licenses[0].license: must be valid to one and only one schema, but 0 are valid","$.components[6].licenses[0].license: required property 'id' not found","$.components[6].licenses[0].license: required property 'name' not found","$.components[6].licenses[0]: must be valid to one and only one schema, but 2 are valid with indexes '0, 1'","$.components[7].licenses[0].license: must be valid to one and only one schema, but 0 are valid","$.components[7].licenses[0].license: required property 'id' not found","$.components[7].licenses[0].license: required property 'name' not found","$.components[7].licenses[0]: must be valid to one and only one schema, but 2 are valid with indexes '0, 1'","$.components[7].licenses[1].license: must be valid to one and only one schema, but 0 are valid","$.components[7].licenses[1].license: required property 'id' not found","$.components[7].licenses[1].license: required property 'name' not found","$.components[7].licenses[1]: must be valid to one and only one schema, but 2 are valid with indexes '0, 1'","$.components[8].licenses[0].license: must be valid to one and only one schema, but 0 are valid","$.components[8].licenses[0].license: required property 'id' not found","$.components[8].licenses[0].license: required property 'name' not found","$.components[8].licenses[0]: must be valid to one and only one schema, but 2 are valid with indexes '0, 1'","$.components[8].licenses[1].license: must be valid to one and only one schema, but 0 are valid","$.components[8].licenses[1].license: required property 'id' not found","$.components[8].licenses[1].license: required property 'name' not found","$.components[8].licenses[1]: must be valid to one and only one schema, but 2 are valid with indexes '0, 1'","$.components[9].licenses[0].license: must be valid to one and only one schema, but 0 are valid","$.components[9].licenses[0].license: required property 'id' not found","$.components[9].licenses[0].license: required property 'name' not found","$.components[9].licenses[0]: must be valid to one and only one schema, but 2 are valid with indexes '0, 1'","$.components[10].licenses[0].license: must be valid to one and only one schema, but 0 are valid","$.components[10].licenses[0].license: required property 'id' not found","$.components[10].licenses[0].license: required property 'name' not found","$.components[10].licenses[0]: must be valid to one and only one schema, but 2 are valid with indexes '0, 1'","$.components[11].licenses[0].license: must be valid to one and only one schema, but 0 are valid","$.components[11].licenses[0].license: required property 'id' not found","$.components[11].licenses[0].license: required property 'name' not found","$.components[11].licenses[0]: must be valid to one and only one schema, but 2 are valid with indexes '0, 1'","$.components[11].licenses[1].license: must be valid to one and only one schema, but 0 are valid","$.components[11].licenses[1].license: required property 'id' not found","$.components[11].licenses[1].license: required property 'name' not found","$.components[11].licenses[1]: must be valid to one and only one schema, but 2 are valid with indexes '0, 1'","$.components[11].licenses[2].license: must be valid to one and only one schema, but 0 are valid","$.components[11].licenses[2].license: required property 'id' not found","$.components[11].licenses[2].license: required property 'name' not found","$.components[11].licenses[2]: must be valid to one and only one schema, but 2 are valid with indexes '0, 1'","$.components[12].licenses[0].license: must be valid to one and only one schema, but 0 are valid","$.components[12].licenses[0].license: required property 'id' not found","$.components[12].licenses[0].license: required property 'name' not found","$.components[12].licenses[0]: must be valid to one and only one schema, but 2 are valid with indexes '0, 1'","$.components[13].licenses[0].license: must be valid to one and only one schema, but 0 are valid","$.components[13].licenses[0].license: required property 'id' not found","$.components[13].licenses[0].license: required property 'name' not found","$.components[13].licenses[0]: must be valid to one and only one schema, but 2 are valid with indexes '0, 1'","$.components[14].licenses[0].license: must be valid to one and only one schema, but 0 are valid","$.components[14].licenses[0].license: required property 'id' not found","$.components[14].licenses[0].license: required property 'name' not found","$.components[14].licenses[0]: must be valid to one and only one schema, but 2 are valid with indexes '0, 1'","$.components[15].licenses[0].license: must be valid to one and only one schema, but 0 are valid","$.components[15].licenses[0].license: required property 'id' not found","$.components[15].licenses[0].license: required property 'name' not found","$.components[15].licenses[0]: must be valid to one and only one schema, but 2 are valid with indexes '0, 1'"]} (status: 400)
```

Thank you in advance for your support :)

### CODE REVIEW

**Comment by takumakume** [comment]
@LucasVanHaaren

The recently generated SBOMReport was in the following format. 
https://github.com/takumakume/sbomreport-to-dependencytrack/pull/19

The format of the license is slightly different. Can I use this test data?

**Comment by LucasVanHaaren** [comment]
Hello @takumakume,

Sorry for the delay, was a bit busy...
Just tried with the new format of SBOMreport you mentionned and it works well this my additions !

```bash
cat testdata/v1alpha1.json | go run main.go --base-url "<TRUNCATED>" --api-key "<TRUNC>" --project-name "test-for-pr" --project-version "v1" --parent-name "PARENT"
2024/08/06 17:11:11 Uploading BOM: project test-for-pr:v1
2024/08/06 17:11:11 Polling completion of upload BOM: project test-for-pr:v1 token 40f1bf18-1f00-498f-bb69-567ad9404576
2024/08/06 17:11:12 BOM upload completed: project test-for-pr:v1 token 40f1bf18-1f00-498f-bb69-567ad9404576
```

**Comment by LucasVanHaaren** [comment]
Hello @takumakume,

I fixed the `TestUpload_Run` which was failing !
Now the whole test suite passed

**Comment by takumakume** [comment]
Sorry for the delay, but I checked!
Thank you for the contrib!

This PR will be merged.
In Dtrack 4.12, there was a phenomenon that when a tag was specified with parentName and parentVersion specified, it became a non-child Project.

**Pull request merged**
